sudo: 
- required

services:
 - docker                      

before_install:
- sudo apt-get update
- chmod +x ./tests/run_tests.sh
                                        
script:
- sudo docker run centos6 /bin/bash -c \
  "exec ${TRAVIS_BUILD_DIR}/tests/run_tests.sh" 
