sudo: 
- required

services:
 - docker                      

before_install:
- sudo apt-get update
- chmod +x ./tests/run_tests.sh
                                        
script:
- sudo docker run --rm=true -v ${TRAVIS_BUILD_DIR}:rw centos:6 /bin/bash -c \
  "exec ${TRAVIS_BUILD_DIR}tests/run_tests.sh" 
