sudo: 
- required

services:
 - docker                      

before_install:
- sudo apt-get update
- chmod +x ./tests/run_tests.sh
                                        
script:
- sudo docker run -v ${TRAVIS_BUILD_DIR}:/${TRAVIS_REPO_SLUG}:ro centos:6 /bin/bash -c "${TRAVIS_BUILD_DIR}/tests/run_tests.sh" 
